var One = "Candy";
alert (One + " This : " + typeof(One));
console.log(typeof(One));
var Three = 7;
alert (Three + " This : " + typeof(Three));
console.log(typeof(Three));
var Five = false;
alert (Five + " This : " + typeof(Five));
console.log(typeof(Five));
var Seven = [55,15,13 , 22];
alert (Seven + " This : " + typeof(Seven));
console.log(typeof(Seven));
var Nine = null;
alert(Nine + " This : " + typeof (Nine));
console.log(typeof(Nine));
var Eleven  = undefined;
alert(Eleven + " This : " + typeof(Eleven));
console.log(typeof(Eleven));
var Thirteen = [1,'Bob','Steve',10];
alert(Thirteen +"This : " + typeof (Thirteen));
console.log(typeof (Thirteen));